

topic_prompt_template = """
You are an expert educational content designer.

Your task is to help retrieve **realistic educational visuals** from the web for the topic **"{topic}"**.

Instructions:
- You will be given text chunks related to the topic.
- Analyze all chunks holistically.
- Identify 1 to 3 key visualizable concepts.
- Based on the concepts, suggest **1 to 3 visual descriptors** that are suitable for web image retrieval.
- These images will be fetched from sources like **DuckDuckGo**
- Later, a separate model (like BLIP2) will describe the retrieved image and generate audio captions — so your job is just to suggest the most **searchable visual ideas**.
-- If only 1 or 2 are needed, output fewer.
-**Give as simple and efficient as possible which can be retrieved from the web**

Important Notes:
- Your descriptors must be **web-search friendly**, realistic, and likely to return good visuals.
- Do NOT suggest fictional or AI-specific styles like “a digital painting” or “ultra-detailed 4K illustration”.
- You **can suggest things like graphs, real-world scenes, physical experiments**, etc., if they are commonly found online.
- If you mention a physics diagram or formula chart, clarify that it's **just a reference to what's expected to be found** on the web.

Return format strictly as:
{{
  "image1": "<descriptor 1>",
  "image2": "<descriptor 2>",
  "image3": "<descriptor 3>"
}}

Rules:
- If one image is enough, return only "image1".
- Do not include any narration or explanation — only the descriptors.
- Do not use JSON formatting or code — just follow the shown format.

Content Chunks:
{chunks}
"""


speech_prompt_template = """
You are an expert educator.

You are shown an image related to the topic: **"{topic}"**.

You are provided with:
- A **caption**: a textual description generated by a vision-language model (may be vague or incorrect).
- **Extracted text**: raw OCR results from the image (may be messy or incomplete).
- **Chunks**: trusted educational content related to the topic.

Your task is to write a short, **educational audio narration (max 3 sentences-100 words)** that clearly explains the image for a learner. 

Guidelines:
- Use the **caption** only if it seems valid and relevant.
- It can interpret the graph plots or flowcharts as **persons body or object** then ignore the caption.
- Use the **OCR text** to understand any visible formulas, labels, or structure — but ignore gibberish.
- Use the **chunks** to ground your explanation in actual academic content.
- Only use the relevant parts of the chunks that relate to the image.
- Do **not** assume anything beyond what can be inferred from the image and the chunks.
- Explain what's happening **visually**, like describing a process flow, a graph trend, or what a diagram shows.
- Avoid technical fluff. Be clear, concise, and engaging.
- Start with phrases like **"In this image..."**, **"You can see..."**, or **"The diagram illustrates..."**



Return only the narration .Do not include any labels,prefixes,or formatting

---


rules:
- Do not use JSON formatting or code or heading or sub-headings — just follow the shown format
- just give the speech (i.e if it starts from "in this image..." the output should start with "In this image...")

**Caption**:
{caption}

**Extracted Text**:
{ocr_text}

**Content Chunks**:
{chunks}

---

Please write a narrated speech for this visual (up to 3 sentences):
"""


